### ISSUE TITLE
Thanasis - Comments/Questions on the Tool (15-06-2018)

### ISSUE THREAD

**Issue by athmegaritis** [andrejadd/AirExplorer#1] opened 2018-06-15 11:27 UTC
**"MAP" Panel**
- Option to change the validity (from 75% to higher or lower values)
- Station Pop up Windows: Could we add the type of station and the station area ("Air Quality Zones" in the tool)?
- In the left panel could we add the Station Type - and Station area as selected options?

**Data Cart**
- In the "Locations" option, could we add cities under each country? For example if i want to analyse Berlin, Munich, Hamburg to have the option to go to Germany and select this cities. At the moment, the city list is too long and difficult to find cities at the end (e.g., Warsaw)
- Could we change "Air Quality Zones" to "Station Area"?
- The names of some cities are not displayed correctly (e.g., ABANTO CIA%)
- Would you give me an example of how i can use the "custom"option?
- What will be the final format of the aggregations? For example, if i click on Average i have Day, Month, Year and then if i click on Month i will have the option to select the month i want to analyse? Or this will be applied only for Years?
- Would be possible to add any other statistical values (e.g., max, or number of exceedances)? 
- Save button for my Data Cart?

**"Chart Explorer"**
"I tried to create some example data sources and produce the figures and I will mention some "strange" results i noticed"

**Bar Charts**
**- Case 1: PM2.5 - BE/FR/GR/ - X axis Country - Grouping by Country**
Result 1: Only Belgium was displayed 
Result 2: Without grouping, only two values for each country were displayed. I don't know what's the year they refer.

**General Question: Why when I press "back" in the preview chart, I lose the averaged time?**

**Case 2: PM2.5-/BE/FR/GR/ + traffic + urban - Group: None - X axis Country**
Result: I take result for all EU countries separately

**Case 3: Same as Case 2 but grouping by country:**
Result: Again all countries

**Case 4: Same as Case 2 but grouping by station type**
Result: Splitted by every station type, even industrial that are not in my selection

**General Question: Would it be possible to have two combined options for grouping, for example country + station type?**

**General Question: Would it be possible to have as an option the whole EU together with the individual countries?**

**Case 5: PM2.5 - BE/FR/GR + traffic - X axis - Group: None**
Result: For all EU Countries separately

**Case 6: Same as 5 but grouping by station type:**
Result: For every station type, even for those that i have not selected in the data source

 **Line Chart**
**Case 7: NO2 - GE/FR -+ Traffic - Group by Country:**
Result: For all EU countries separately

**Case 8: Same as 7 but grouping by station type**
Results for all stations

**Case 9: NO2 - BE/FR/GR) + traffic - No grouping**
Result: Only one line. Max point in 1975. Even using only one country i take the same figure

**Case 10: NO2 - FR - Grouping by Station Type**
Result: Is any reason of not having results from traffic stations after 2012. I checked the E-Reporting website and there are NO2 measurements from traffic stations in recent years.

**Comment by andrejadd** [comment] 2018-10-25 19:34
**Note**: I added my comments to each case in italics inside square brackets: *[AA: ]*


**Case 1**
 PM2.5 - BE/FR/GR/ - X axis Country - Grouping by Country

- Result 1: Only Belgium was displayed. *[AA: Not observed anymore]*
- Result 2: Without grouping, only two values for each country were displayed. I don't know what's the year they refer *[AA: The x-axis has to be set to Time Point, otherwise aggregation takes place over the years]*.
- General Question: Why when I press "back" in the preview chart, I lose the averaged time? *[AA: Not clear where this is lost]*.

**Case 2** 
PM2.5-/BE/FR/GR/ + traffic + urban - Group: None - X axis Country
        
- Result: I take result for all EU countries separately *[AA: Not observed anymore, this chart was produced:]*

![pm25_befrgr_traffic_urban_boxplot](https://user-images.githubusercontent.com/12441470/47525051-a7546f00-d872-11e8-9447-c447f421d9f3.png)
        
**Case 3**
Same as Case 2 but grouping by country

- Result: Again all countries *[AA: Not observed anymore. Note that selected Country as X-Axis and Country as Grouping will place empty groups in each x-axis country slot]*

**Case 4**
Same as Case 2 but grouping by station type

- Result: Splitted by every station type, even industrial that are not in my selection *[AA: not observed  anymore]*

**Case 5**
PM2.5 - BE/FR/GR + traffic - X axis - Group: None

- Result: For all EU Countries separately *[AA: not observed anymore]*

**Case 6**
Same as 5 but grouping by station type

- Result: For every station type, even for those that i have not selected in the data source *[AA: not observed anymore]*

**Case 7**
NO2 - BE/FR - Traffic - Group by Country

- Result: All countries are displayed *[AA: Fixed by changing the AND/OR logic in the SQL query - Should now only display BE and FR]*

**Case 8**
Same as 7 but grouping by station type

- Results for all stations: *[AA: Not observed anymore]*

**Case 9**
NO2 - BE/FR/GR - traffic - No grouping   

- Result: Only one line *[AA: This is by design, i.e. the mean is taken over all stations on default, which includes stations from these countries. Use grouping to separate into countries]*
- Max point in 1975 *[AA: Not observed. It starts with year 1988 now]*
- Even using only one country i take the same figure *[AA: Not observed anymore. Different charts for BE/FR/GR vs BE can be charted]*

**Case 10**
NO2 - FR - Grouping by Station Type

- Result: Is any reason of not having results from traffic stations after 2012. I checked the E-Reporting website and there are NO2 measurements from traffic stations in recent years *[AA: Not observed anymore]*
- With the updated data set there are indeed measurements:

![no2_fr_yearlymean](https://user-images.githubusercontent.com/12441470/47525405-8d675c00-d873-11e8-94b5-41b1a6f6ef8b.png)

**Closed** 2018-11-22 15:48 UTC
